### ISSUE TITLE
Auto login, without 'login' button click

### ISSUE THREAD

**Issue by ZMilosevich** [dopry/svelte-auth0#23] opened 2021-11-17 11:47 UTC
Hi, on landing page I tried to execute auto 'login' function (without login btn click),
login(auth0Promise, preseveRoute = true, callback_url = null)

definitely I am doing something wrong, any code sample will be helpful

`  import { onMount, tick } from "svelte";
  import config from "../js/authConfig";

  import {
    Auth0Context,
    Auth0LoginButton,
    Auth0LogoutButton,
    authError,
    authToken,
    idToken,
    isAuthenticated,
    isLoading,
    userInfo,
  } from "@dopry/svelte-auth0";

  onMount(() => {
    Auth0LoginButton.login(auth0Promise, preseveRoute = true, callback_url = null)
  });`

**Comment by dopry** [comment] 2023-02-15 15:24
I believe this is a duplicate of https://github.com/dopry/svelte-auth0/issues/16. The auto login, aka SilentRenew, requires that you use your own keys and not the Auth0 developer keys.

**Closed as completed by dopry** 2023-02-15 15:24 UTC
